const express = require('express')
const router = express.Router()
const asyncHandler = require('../utils/asyncHandler')
const driverController = require('../controllers/driverController')
const orderRatingController = require('../controllers/orderRatingController')

router.get('/dashboard', asyncHandler(driverController.getDashboard))
router.patch('/status', asyncHandler(driverController.updateStatus))
router.post('/status', asyncHandler(driverController.updateStatus))
router.patch('/account', asyncHandler(driverController.updateAccount))
router.get('/profile', asyncHandler(driverController.getProfile))
router.patch('/profile', asyncHandler(driverController.updateProfile))
router.get('/income/summary', asyncHandler(driverController.getIncomeSummary))
router.get('/settlements', asyncHandler(driverController.listDriverSettlements))
router.get('/settlement-payments', asyncHandler(driverController.listDriverSettlementPayments))
router.get('/ratings', asyncHandler(orderRatingController.listDriverRatings))
router.get('/orders', asyncHandler(driverController.listDriverOrders))
router.patch('/orders/:id/accept', asyncHandler(driverController.acceptAssignedOrder))
router.patch('/orders/:id/reject', asyncHandler(driverController.rejectAssignedOrder))
router.post('/withdrawals', asyncHandler(driverController.createWithdrawal))
router.get('/withdrawals', asyncHandler(driverController.listWithdrawals))
router.get('/list', asyncHandler(driverController.getDriverList))
router.post('/:id/approve', asyncHandler(driverController.approveDriver))
router.post('/:id/reject', asyncHandler(driverController.rejectDriver))
router.post('/:id/ban', asyncHandler(driverController.banDriver))

module.exports = router
